[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "Creating our own maze generating algorithms and maze solving algorithms"
readme = {file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "omarquez", email = "omarquez@student.42urduliz.com"},
    {name = "jrecio-t", email = "jrecio-t@student.42urduliz.com"},
]
requires-python = ">=3.10"
